---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
  namespace: egs-eventfinder
spec:
  selector:
    matchLabels:
      app: booking-db
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      containers:
      - name: booking-db
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: booking-db
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookingdb-secrets
              key: db_password
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: booking-pvc-claim
---
apiVersion: v1
kind: Service
metadata:
  name: booking-db
  namespace: egs-eventfinder
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: booking-db
  selector:
    app: booking-db
  type: NodePort