version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_booking
      MYSQL_USER: fastmiguel099
      MYSQL_PASSWORD: 12345
    ports:
      - '3306:3306' 
    expose:
      - '3306' 
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db:
    driver: local