apiVersion: v1
kind: Pod
metadata:
  name: mysql-wakeup
  namespace: egs-eventfinder
spec:
  containers:
    - name: cron-container
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args:
        - -c
        - |
          while true; do
            wget -O - http://bookingapi.deti/ticket/user/tickets?user_id=1
            sleep 4h
          done
  restartPolicy: Never
